name: tcga-methylation-targeted
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.3.2
  - r-data.table=1.15.4
  - r-ggplot2=3.5.1
  - r-cowplot=1.1.3
  - r-yaml=2.3.10
  - r-reshape2=1.4.4
  - bioconductor-minfi=1.48.0
  - bioconductor-annotationdbi=1.66.0
  - bioconductor-org.hs.eg.db=3.18.0
  - bioconductor-illuminaHumanMethylation450kanno.ilmn12.hg19=0.6.0
  - bioconductor-illuminaHumanMethylationEPICanno.ilm10b.hg19=0.6.0
  - r-lintr=3.1.2
